### ISSUE TITLE
Highlighting breaks multiline statements

### ISSUE THREAD

**Issue by sequitur** [hexojs/hexo-util#10]
Say we have a code block in a language that supports multiline comments or strings, such as Coffeescript:

``` coffeescript
myFunc """
  This is a
  string that
  spans multiple
  lines.
"""
```

Hexo will render the following html:

``` html
<figure class="highlight coffeescript">
  <table>
    <tbody>
      <tr>
        <td class="code">
          <pre>
            <span class="line">myFunc <span class="string">"""</span><br>
            <span class="line">  This is a</span><br>
            <span class="line">  string that</span><br>
            <span class="line">  spans multiple</span><br>
            <span class="line">  lines.</span><br>
            <span class="line">"""</span></span><br>
          </pre>
        </td>
      </tr>
    </tbody>
  </table>
</figure>
```

This seems to prevent hljs from properly inserting `<span>` elements. I'll admit I don't understand what [this line](https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L36), which adds the `.line` spans, is supposed to accomplish (ie, why do we want each line wrapped in its own span in the first place), but it's doing it in a naive way that doesn't account for existing `span` elements that span more than one line. What it should produce is:

``` html
<figure class="highlight coffeescript">
  <table>
    <tbody>
      <tr>
        <td class="code">
          <pre>
            <span class="line">myFunc <span class="string">"""</span></span><br>
            <span class="line string">  This is a</span><br>
            <span class="line string">  string that</span><br>
            <span class="line string">  spans multiple</span><br>
            <span class="line string">  lines.</span><br>
            <span class="line string">"""</span><br>
          </pre>
        </td>
      </tr>
    </tbody>
  </table>
</figure>
```

...which would be correctly highlighted.

**Comment by yscoder** [comment]
**Another example:**

This is a java documentation comment.
```java
/**
*  @param args
*/
```
Rendering results:

![image](https://cloud.githubusercontent.com/assets/12295378/17167810/a66ecb54-5411-11e6-9fb2-fb436b5b6711.png)

This class `.comment` does not apply to multi-line.

**Comment by RoeeXu** [comment]
`npm WARN deprecated swig@1.4.2: This package is no longer maintained
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo/bin/hexo

> dtrace-provider@0.8.0 install /usr/local/lib/node_modules/hexo/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: not found
npm WARN install:dtrace-provider@0.8.0 dtrace-provider@0.8.0 install: `node scripts/install.js`
npm WARN install:dtrace-provider@0.8.0 spawn ENOENT

> hexo-util@0.6.0 postinstall /usr/local/lib/node_modules/hexo/node_modules/hexo-util
> npm run build:highlight


> hexo-util@0.6.0 build:highlight /usr/local/lib/node_modules/hexo/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

sh: 1: node: not found

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:highlight"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hexo-util@0.6.0 build:highlight: `node scripts/build_highlight_alias.js > highlight_alias.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 build:highlight script 'node scripts/build_highlight_alias.js > highlight_alias.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build_highlight_alias.js > highlight_alias.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/hexo/node_modules/hexo-util/npm-debug.log
/usr/local/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /hexo/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "hexo"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/roee/npm-debug.log
npm ERR! code 1
`
