### ISSUE TITLE
Add mark support to highlight()

### ISSUE THREAD

**Issue by lotabout** [hexojs/hexo-util#11]
When writing codes, sometimes we'll need to highlight some lines like:

![selection_035](https://cloud.githubusercontent.com/assets/1527040/13102145/b829b9ee-d586-11e5-84c9-5dd13d290853.png)

As for how to specify the lines, we could follow [octpress' rules](http://octopress.org/docs/plugins/backtick-codeblock/), i.e.

> mark:#,#-# - Mark one or more lines of code with the class name "marked". Accepts one number, numbers separated by commas, and number ranges. Example mark:1,5-8 will mark lines 1,5,6,7,8. Note: If you've changed the beginning line number be sure these match rendered line numbers 

As hexo depends on hexo-util for highlighting, we should add mark support into hexo-util. The syntax part can later be added into hexo's tag plugin.

**Comment by leesei** [comment]
Thanks.

**Comment by leesei** [comment]
@tommy351 please publish new version to npm
