### ISSUE TITLE
escapeHTML escape ' and ` character

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo-util#113]
https://github.com/hexojs/hexo-util/blob/b2923326f0e9d7fd7b0cf947fbf90bea835e9c7d/lib/escape_html.js#L5-L12

Should we escape `'` and ``` ` ``` character as well?

**Comment by curbengh** [comment]
+1 on escape single-quote, it's also recommended by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#rule-1---html-escape-before-inserting-untrusted-data-into-html-element-content).

I would imagine backquote can be used to escape javascript.
