### ISSUE TITLE
Drop node-html-entities

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo-util#127]
https://github.com/hexojs/hexo-util/blob/42b7393b9c591d3874e0c687b4dba5a17512121a/lib/highlight.js#L79

hexo-utils built-in highlight is using `node-html-entities`, a lib that hasn't been active for last 4 years.

I might take a look at this and try to drop this dependency.

**Comment by curbengh** [comment]
[`escapeHTML()`](https://github.com/hexojs/hexo-util/blob/71fce3f329b1a25b4edac6ce4c193f29dde95a30/lib/escape_html.js#L6-L12) also escape more characters than [node-html-entities](https://github.com/mdevils/node-html-entities/blob/fb9cce4d5113508e297c660b29f1b995571b5aff/lib/xml-entities.js#L23-L27).
