### ISSUE TITLE
hexo code block highlight error?

### ISSUE THREAD

**Issue by nella17** [hexojs/hexo-util#151]
I found a code highlight error in new version hexo.
In this commit 401dde1621331d07ce52caf37c94951bac33ddb7, @stevenjoezhang change code block highlight renderer, but this make error render for code block highlight.

![capture node](https://user-images.githubusercontent.com/14134195/70021847-08e62180-15cd-11ea-83c5-76264e07beab.png)

**Comment by stevenjoezhang** [comment]
It's a bug of the theme that you're using. `highlight` of `hexo-util` only generates html, the style is controlled by the theme.

**Comment by nella17** [comment]
Sorry, I found bugs in theme.
