### ISSUE TITLE
toc helper should not parse the text of children element(s)

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-util#174]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Fix the toc helper to select only text content and not other sub-elements like links.

In depth explanation here: https://github.com/hexojs/hexo-renderer-markdown-it/issues/102

**Comment by SukkaW** [comment]
@curbengh 

```html
<h1 id="title-3"><span>Title</span> 3</h3>
```

In this case `Title 3` is what we needed for `text`.

**Comment by curbengh** [comment]
@SukkaW 

Since the output is `'\n#\nCreate a new post\n'`, what if tocObj trim the newlines and anything before and after them? It maybe more appropriate to trim in toc helper, since user might want to retain the original (rare, but possible).

**Comment by SukkaW** [comment]
@curbengh 

```html
<h3 id="create-a-new-post">
<a class="header-anchor" href="#create-a-new-post">#</a>Create a new post
</h3>
```

will become `\n#Create a new post\n`. Still not appropriate.

**Comment by curbengh** [comment]
Looks like a common question in cheerio/jquery, 

- https://stackoverflow.com/questions/20832910/get-text-in-parent-without-children-using-cheerio
- https://www.designcise.com/web/tutorial/how-to-get-html-elements-text-excluding-children-using-jquery-and-javascript

Seems possible to fix, if htmlparser has the equivalent function of native DOM's `document.childNodes` or cheerio's `$.first()`.

**Comment by Microbai** [comment]
When contents likes this 
```html
<h2><span id="title_1">title 1</span></h2>
```
 tocObj won't parse the correct id, So I edit the getId function, then work.
```js
const getId = ele => {
  const { id } = ele.attribs;
  const { children } = ele;
  return id || (!children[0] ? null : getId(children[0]));
};
```

**Comment by SukkaW** [comment]
@Microbai `tocObj()` is not designed to get id from child element but only from parent element.

**Comment by Microbai** [comment]
@SukkaW I Knew it.But when I use Hexo 4.2, the page can't render toc correctly.So I edit tocObj for now, and it works.
