### ISSUE TITLE
Having trouble getting highlightjs working in hexo-util

### ISSUE THREAD

**Issue by dylanilvento** [hexojs/hexo-util#222]
I've been trying to incorporate Highlightjs into my hexo project and discovered that it's a part of hexo-util. I installed the plugin via npm but the readme doesn't give a lot of info as to how I'm supposed to get it up and running, outside of running `var util = require('hexo-util')`, which I have in a `js` file in my `scripts` folder. I've scoured the Internet for a tutorial or another project that will show me how to activate Highlightjs, but I haven't had a clear cut answer.

The readme says that the syntax for highlight in hexo-util is `highlight(str, [options])`, but it's unclear where that command goes. I've found conflicting info that it might go in a `js` file in the `script` directory, inside the post's `md` file itself, or even in `_config.yml`?

Also unclear what the `str` parameter in `highlight` is supposed to be either. Is this the code block that you're formatting? If that's the case, then _should_ the `highlight` call go in the `md` file? I tried that, but to no avail. I currently have this test code in one of my posts:

```
` ` `csharp
public int test = 1 + 1;
` ` `
```

It shows up in my post without any syntax highlighting, even though the `highlight` class does show up in the HTML. I know newer versions of Highlightjs actually use the `hljs` class, but no amount of prodding with these keywords has gotten me anywhere.

I would love some help with this!

**Comment by SukkaW** [comment]
The best way to use `highlight` utility is not to use it. Use Hexo's built-in highlight feature directly.

**Comment by dylanilvento** [comment]
Ok, how do I do that? Using the standard three backtick markdown codeblock just shows an unhighlighted codeblock on my post.

**Comment by SukkaW** [comment]
Read the Hexo documentation about how to enable `highlight.js` feature:

https://hexo.io/docs/configuration#Writing

**Comment by dylanilvento** [comment]
Alright, that seems to have gotten it working! I had to set `hljs: true` and I still had to include calls to highlight.js's CSS, so I wish that was more clear in the documentation. Is there a way to switch the color palette of the syntax highlighting to the other palettes like `atom-dark`?

**Comment by stevenjoezhang** [comment]
You can load CSS in the webpage:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/atom-one-dark.css">
```
