### ISSUE TITLE
hexo install failed

### ISSUE THREAD

**Issue by sheacoding** [hexojs/hexo-util#23]
log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:highlight' ]
2 info using npm@4.4.1
3 info using node@v7.7.3
4 verbose config Skipping project config: /home/shea/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/shea/package.json'
6 verbose cwd /home/shea
7 verbose Linux 4.9.16-1-MANJARO
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:highlight"
9 verbose node v7.7.3
10 verbose npm  v4.4.1
11 error path /home/shea/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/shea/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/shea/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

OS: manjaro i3 17.0

**Comment by NoahDragon** [comment]
As the message indicates, it is mostly likely a problem with npm itself. Hexo couldn't do much about it.

**Comment by demurgos** [comment]
There's another issue with more comments for this problem: https://github.com/hexojs/hexo-util/issues/24
