### ISSUE TITLE
Where is the querystring's unscape?

### ISSUE THREAD

**Issue by Frodez** [hexojs/hexo-util#235]
There is the source code:
https://github.com/hexojs/hexo-util/blob/19315b88106a16dece34521977096e60273b80da/lib/encode_url.js#L4

However, There is no import for the package `querystring`, and the package [querystring](https://github.com/Gozala/querystring) don't have the method which is `unscape`.

Where is the querystring's unscape?

**Comment by stevenjoezhang** [comment]
querystring is a built-in package: https://nodejs.org/dist/latest-v14.x/docs/api/querystring.html#querystring_querystring_unescape_str
