### ISSUE TITLE
 this fails on your system: npm ERR!     npm run build:highlight

### ISSUE THREAD

**Issue by zengyee** [hexojs/hexo-util#24]
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.8.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "hexo-cli" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jeffrey/github/codeleague.github.io/npm-debug.log
npm ERR! code 1

**Comment by NoahDragon** [comment]
Does `/usr/bin/nodejs` exist?

https://github.com/hexojs/hexo/issues/2095

**Comment by waterzhou** [comment]
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexo-util@0.6.0 postinstall script 'npm run build:highlight'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:highlight
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /work/hardware/ESP32/npm-debug.log
npm ERR! code 1

I also encounter the same problem.  And I also checked usr/bin/nodejs existed indeed.

**Comment by NoahDragon** [comment]
@waterzhou this issue is really hard to reproduce, and it is usually related to the system/npm environment.

**Comment by disburden** [comment]
same question

**Comment by sky-admin** [comment]
same question +1, windows 10,node 8,npm 5.4

**Comment by demurgos** [comment]
Possibly related issue: https://github.com/hexojs/hexo-cli/issues/23

Someone mentioned a Docker file to reproduce this issue: https://github.com/hexojs/hexo-cli/issues/23#issuecomment-326904290

More generally, could you explain the rationale for running a postinstall hook? The main use case I see is if you have a system dependent build that you absolutely can't run during the publish step. Here you're just generating a `.json`. A better solution would be to use a `prepare` hook (that runs during before publication to npm, or when installing this package as the top-level package, for development for example).

**Comment by demurgos** [comment]
@NoahDragon I sent [a PR to solve this issue](https://github.com/hexojs/hexo-util/pull/28). Could you take a look at it?

**Comment by NoahDragon** [comment]
@demurgos Thank you very much. I will have a look.
