### ISSUE TITLE
Missing support for highlighting F# code

### ISSUE THREAD

**Issue by realvictorprm** [hexojs/hexo-util#27]
Hello :)

So far I saw this is the plugin which provides the syntax highlighting for Hexo.
I noticed during using it that F# syntax highlighting is only supported for some usual keywords.

How could this be improved effectively?

**Comment by NoahDragon** [comment]
As the highlighting feature is from highlight.js, there is nothing Hexo can do about it. Have you tried the https://github.com/ele828/hexo-prism-plugin ? It uses different syntax renderer.

**Comment by alxbl** [comment]
F# is supported according to the latest (9.12.0) version of highlight.js.

See [Highlight.js Supported Languages](https://highlightjs.org/static/demo/)

The language is called `fsharp` when you do backtick blocks or via the `codeblock` tag:

```
{% codeblock lang:fsharp %}
....
{% endcodeblock %}
```

**Comment by realvictorprm** [comment]
Thank you!

----

Official member of the F# Board of Trustee's. F# for fun and profit!


Am 11.12.2017 18:27 schrieb "Alexandre Beaulieu" <notifications@github.com>:
