### ISSUE TITLE
Parsing code for YouTube Tag Plugin

### ISSUE THREAD

**Issue by bennycode** [hexojs/hexo-util#381]
Hello, I am looking for the code responsible parsing [YouTube tags](https://hexo.io/docs/tag-plugins#YouTube). I found [youtube.ts](https://github.com/hexojs/hexo-tag-embed/blob/v1.0.0-rc.1/lib/tags/youtube.ts) in [hexo-tag-embed](https://github.com/hexojs/hexo-tag-embed) but it only consumes already parsed information. 

Do you know where I can actually find the regex that splits a `{% youtube ... %}` tag?

**Comment by uiolee** [comment]
I don't understand what you want, but I guess [youtube.ts](https://github.com/hexojs/hexo-tag-embed/blob/v1.0.0-rc.1/lib/tags/youtube.ts) is a way to parse YouTube Tag.

BTW, you should post this question in [discussion/Q&A](https://github.com/orgs/hexojs/discussions/categories/question-answer)

**Comment by stevenjoezhang** [comment]
Hexo uses Nunjucks for document preprocessing, so you can find how it processes tags in the Nunjucks source code.

**Comment by bennycode** [comment]
Thank you! This aligns with the comment from here: https://github.com/hexojs/hexo-tag-embed/issues/1#issuecomment-1768968172 👍
