### ISSUE TITLE
Setting highlight: gutter to false in the config doesn't work

### ISSUE THREAD

**Issue by mattbruv** [hexojs/hexo-util#40]
Disabling the gutter should make it so that highlightjs doesn't include line numbers.
The [highlightUtil](https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js#L13) function expects a string of `'gutter'`: 
```js
var gutter = options.hasOwnProperty('gutter') ? options.gutter : true;
```
But even when you disable it in the config it somehow doesn't work. Changing other settings like `hljs` work just fine, but gutter won't.

```yaml
highlight:
  hljs: true
  gutter: false
```
Not sure why the config remembers some settings like `hljs` but not `gutter`. Right now I have to go into node_modules and find this file and manually set gutter to false in order to get rid of it.

**Comment by curbengh** [comment]
[`line_number`](https://github.com/hexojs/hexo/blob/087b3fa456aa97279df61a7f05e59c932051ee2b/lib/plugins/filter/before_post_render/backtick_code_block.js#L19) is parsed as `gutter`. Please use

``` yml
highlight:
  line_number: false
```

**Comment by stevenjoezhang** [comment]
Closing as answered.
