### ISSUE TITLE
why use  '(.+?)'  instead of '(.*?)'?

### ISSUE THREAD

**Issue by reverland** [hexojs/hexo-util#7]
I have a question. Why https://github.com/hexojs/hexo-util/blob/master/lib/permalink.js#L28 must return 

      return '(.+?)';

rather than

    return '(.*?)';
      
I tried to fix it when there is no title but `:title` is specified in permalink.

https://github.com/reverland/hexo-util/pull/1

I don't know if I missed something.

**Comment by NoahDragon** [comment]
We do not recommend to put empty string in permanlink. This may cause different pages have same url.

**Comment by reverland** [comment]
@NoahDragon Yeah, I prefer hexo's way,

It just to be a problem when some one migrate their blogs from other system.

**Comment by NoahDragon** [comment]
@reverland Agree.
