### ISSUE TITLE
highlight.js doesn't detect yaml

### ISSUE THREAD

**Issue by LouisBarranqueiro** [hexojs/hexo-util#8]
highlight.js doesn't detect yaml, it's displayed as plain text. It seems that bug doesn't come from highlight since it works well on their [demo website](https://highlightjs.org/static/demo/)

**Comment by tufu9441** [comment]
I have the same problem, when I declare a codeblock with YAML, it outputs as plain text, just as following:
![](https://camo.githubusercontent.com/f7b2c19772006dd1c781d125a8437c9789d724a3/687474703a2f2f692e696d6775722e636f6d2f4a6f48717354622e706e67)

**Comment by leesei** [comment]
I'm on 3.2 and it can highlight  ```` ```yaml ```` code block.
Care to test again?

**Comment by leesei** [comment]
BTW, auto detect is turned off by default for it causes many problems.

**Comment by LouisBarranqueiro** [comment]
Wow! I forgot this issue. Yeah, It works now
